name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a YieldCurve with...
        2. Call interpolate() with...
        3. Observe the error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproducible Example
      description: If possible, provide a minimal code example that demonstrates the issue.
      placeholder: |
        ```rust
        use pricer_core::yield_curve::YieldCurve;

        fn main() {
            // Your code here
        }
        ```
      render: rust
    validations:
      required: false

  - type: dropdown
    id: crate
    attributes:
      label: Affected Crate(s)
      description: Which crate(s) are affected by this bug?
      multiple: true
      options:
        - pricer_core (L1)
        - pricer_models (L2)
        - pricer_pricing (L3)
        - pricer_risk (L4)
        - Unknown / All
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.75.0 (82e1608df 2023-12-21)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: e.g., Ubuntu 22.04, Windows 11, macOS 14.0
      placeholder: "Ubuntu 22.04"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.).
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't already been reported.
          required: true
        - label: I have provided a minimal reproducible example (if applicable).
          required: false
