name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "A clear and concise description of what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case(s) where this feature would be valuable.
      placeholder: |
        Example: When calculating XVA for a large portfolio, I need to...
    validations:
      required: true

  - type: textarea
    id: api-proposal
    attributes:
      label: API Proposal (Optional)
      description: If you have ideas about how the API should look, please share.
      placeholder: |
        ```rust
        // Proposed API usage
        let result = pricer.some_new_method(params)?;
        ```
      render: rust
    validations:
      required: false

  - type: dropdown
    id: crate
    attributes:
      label: Target Crate(s)
      description: Which crate(s) would this feature affect?
      multiple: true
      options:
        - pricer_core (L1)
        - pricer_models (L2)
        - pricer_pricing (L3)
        - pricer_risk (L4)
        - New crate
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Assessment)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my project
        - Critical / Blocking
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: "I've tried using X instead, but..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.
      placeholder: "Related papers, similar implementations in other libraries, etc."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature.
          required: false
        - label: I have searched existing issues to ensure this hasn't been requested.
          required: true
