//! Pricer Computation Graph API Handlers
//!
//! This module provides the API endpoint for retrieving computation graphs
//! generated by TracedFloat during pricing calculations.
//!
//! ## Endpoint
//!
//! - `GET /api/pricer/graph` - Get the computation graph for a pricing calculation
//!
//! ## Query Parameters
//!
//! - `detail_level` (optional): Level of detail for the graph
//!   - `operation` (default): Show all individual operations
//!   - `scope`: Aggregate operations into scopes

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::Arc;

use axum::extract::{Query, State};
use axum::http::StatusCode;
use axum::Json;
use num_traits::Float;
use serde::{Deserialize, Serialize};

use pricer_core::types::{
    clear_trace_context, export_graph, set_trace_context, D3Graph, DetailLevel, ExecutionTrace,
    TracedFloat,
};

use crate::web::AppState;

// =============================================================================
// Request Types
// =============================================================================

/// Query parameters for the pricer graph endpoint.
#[derive(Debug, Clone, Deserialize)]
pub struct PricerGraphQueryParams {
    /// Detail level for the graph export.
    /// - "operation" (default): Show all individual operations
    /// - "scope": Aggregate operations into scopes
    #[serde(default = "default_detail_level")]
    pub detail_level: String,

    /// Optional pricing formula to evaluate.
    /// If not specified, a sample Black-Scholes calculation is used.
    #[serde(default)]
    pub formula: Option<String>,
}

fn default_detail_level() -> String {
    "operation".to_string()
}

// =============================================================================
// Response Types
// =============================================================================

/// Response for the pricer graph endpoint.
#[derive(Debug, Clone, Serialize)]
pub struct PricerGraphResponse {
    /// The D3-compatible computation graph.
    #[serde(flatten)]
    pub graph: D3Graph,
}

/// Error response for the pricer graph endpoint.
#[derive(Debug, Clone, Serialize)]
pub struct PricerGraphErrorResponse {
    /// Error type
    pub error_type: String,
    /// Error message
    pub message: String,
}

// =============================================================================
// Sample Pricing Functions
// =============================================================================

/// Black-Scholes d1 calculation using generic Float trait.
fn calculate_d1<T: Float>(spot: T, strike: T, rate: T, vol: T, time: T) -> T {
    let numerator = (spot / strike).ln() + (rate + vol * vol / T::from(2.0).unwrap()) * time;
    let denominator = vol * time.sqrt();
    numerator / denominator
}

/// Black-Scholes d2 calculation.
fn calculate_d2<T: Float>(d1: T, vol: T, time: T) -> T {
    d1 - vol * time.sqrt()
}

/// Simplified Black-Scholes call price calculation.
/// Uses a simplified approximation of the normal CDF.
fn calculate_call_price<T: Float>(spot: T, strike: T, rate: T, vol: T, time: T) -> T {
    let d1 = calculate_d1(spot, strike, rate, vol, time);
    let d2 = calculate_d2(d1, vol, time);

    // Simplified normal CDF approximation: 0.5 * (1 + x / sqrt(1 + x^2))
    let n_d1 = T::from(0.5).unwrap() * (T::one() + d1 / (T::one() + d1 * d1).sqrt());
    let n_d2 = T::from(0.5).unwrap() * (T::one() + d2 / (T::one() + d2 * d2).sqrt());

    let discount = (-rate * time).exp();
    spot * n_d1 - strike * discount * n_d2
}

/// Execute a sample pricing calculation using TracedFloat.
fn execute_sample_pricing() -> ExecutionTrace {
    // Set up trace context
    let trace = Rc::new(RefCell::new(ExecutionTrace::new()));
    set_trace_context(Rc::clone(&trace));

    // Enter main pricing scope
    trace.borrow_mut().enter_scope("black_scholes_price");

    // Create input values
    let spot = TracedFloat::input(100.0, "spot");
    let strike = TracedFloat::input(100.0, "strike");
    let rate = TracedFloat::input(0.05, "rate");
    let vol = TracedFloat::input(0.2, "vol");
    let time = TracedFloat::input(1.0, "time");

    // Calculate d1
    trace.borrow_mut().enter_scope("calculate_d1");
    let d1 = calculate_d1(spot, strike, rate, vol, time);
    trace.borrow_mut().exit_scope();

    // Calculate d2
    trace.borrow_mut().enter_scope("calculate_d2");
    let _d2 = calculate_d2(d1, vol, time);
    trace.borrow_mut().exit_scope();

    // Calculate price
    trace.borrow_mut().enter_scope("calculate_price");
    let _price = calculate_call_price(spot, strike, rate, vol, time);
    trace.borrow_mut().exit_scope();

    // Exit main scope
    trace.borrow_mut().exit_scope();

    // Clear context and return trace
    clear_trace_context();

    // Extract the trace from Rc
    Rc::try_unwrap(trace).unwrap().into_inner()
}

/// Execute a simple arithmetic calculation for testing.
fn execute_simple_calculation() -> ExecutionTrace {
    let trace = Rc::new(RefCell::new(ExecutionTrace::new()));
    set_trace_context(Rc::clone(&trace));

    trace.borrow_mut().enter_scope("simple_calc");

    let a = TracedFloat::input(10.0, "a");
    let b = TracedFloat::input(5.0, "b");
    let c = TracedFloat::input(2.0, "c");

    // (a + b) * c = (10 + 5) * 2 = 30
    let sum = a + b;
    let _result = sum * c;

    trace.borrow_mut().exit_scope();
    clear_trace_context();

    Rc::try_unwrap(trace).unwrap().into_inner()
}

// =============================================================================
// Handler
// =============================================================================

/// GET /api/pricer/graph
///
/// Returns the computation graph for a pricing calculation using TracedFloat.
///
/// # Query Parameters
///
/// - `detail_level` (optional): "operation" (default) or "scope"
/// - `formula` (optional): "black_scholes" (default) or "simple"
///
/// # Response
///
/// Returns a D3.js-compatible graph structure.
pub async fn get_pricer_graph(
    State(_state): State<Arc<AppState>>,
    Query(params): Query<PricerGraphQueryParams>,
) -> Result<Json<PricerGraphResponse>, (StatusCode, Json<PricerGraphErrorResponse>)> {
    // Parse detail level
    let detail_level = match params.detail_level.as_str() {
        "operation" => DetailLevel::Operation,
        "scope" => DetailLevel::Scope,
        other => {
            return Err((
                StatusCode::BAD_REQUEST,
                Json(PricerGraphErrorResponse {
                    error_type: "InvalidDetailLevel".to_string(),
                    message: format!(
                        "Invalid detail_level '{}'. Must be 'operation' or 'scope'.",
                        other
                    ),
                }),
            ));
        }
    };

    // Execute the appropriate pricing calculation
    let trace = match params.formula.as_deref() {
        Some("simple") => execute_simple_calculation(),
        Some("black_scholes") | None => execute_sample_pricing(),
        Some(other) => {
            return Err((
                StatusCode::BAD_REQUEST,
                Json(PricerGraphErrorResponse {
                    error_type: "InvalidFormula".to_string(),
                    message: format!(
                        "Invalid formula '{}'. Must be 'black_scholes' or 'simple'.",
                        other
                    ),
                }),
            ));
        }
    };

    // Export to D3 format
    let graph = export_graph(&trace, detail_level);

    Ok(Json(PricerGraphResponse { graph }))
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_execute_simple_calculation() {
        let trace = execute_simple_calculation();

        // Should have: 3 inputs + 1 add + 1 mul = 5 nodes
        assert_eq!(trace.node_count(), 5);
        // add has 2 edges, mul has 2 edges = 4 edges
        assert_eq!(trace.edge_count(), 4);
        // 1 scope
        assert_eq!(trace.scope_count(), 1);
    }

    #[test]
    fn test_execute_sample_pricing() {
        let trace = execute_sample_pricing();

        // Should have multiple nodes for Black-Scholes calculation
        assert!(trace.node_count() > 10);
        // Should have multiple edges
        assert!(trace.edge_count() > 5);
        // Should have 4 scopes: main + d1 + d2 + price
        assert_eq!(trace.scope_count(), 4);
    }

    #[test]
    fn test_export_simple_calculation() {
        let trace = execute_simple_calculation();
        let graph = export_graph(&trace, DetailLevel::Operation);

        assert_eq!(graph.nodes.len(), 5);
        assert_eq!(graph.edges.len(), 4);
        assert_eq!(graph.metadata.detail_level, DetailLevel::Operation);
    }

    #[test]
    fn test_export_scope_level() {
        let trace = execute_simple_calculation();
        let graph = export_graph(&trace, DetailLevel::Scope);

        // All nodes are in one scope, so should aggregate to 1 node
        assert_eq!(graph.nodes.len(), 1);
    }

    #[test]
    fn test_calculate_d1() {
        let d1 = calculate_d1(100.0_f64, 100.0, 0.05, 0.2, 1.0);
        // d1 should be positive for ATM option with positive rate
        assert!(d1 > 0.0);
    }

    #[tokio::test]
    async fn test_get_pricer_graph_default() {
        let state = Arc::new(AppState::new());
        let params = PricerGraphQueryParams {
            detail_level: "operation".to_string(),
            formula: None,
        };

        let result = get_pricer_graph(State(state), Query(params)).await;
        assert!(result.is_ok());

        let response = result.unwrap();
        assert!(!response.graph.nodes.is_empty());
        assert!(!response.graph.edges.is_empty());
    }

    #[tokio::test]
    async fn test_get_pricer_graph_simple() {
        let state = Arc::new(AppState::new());
        let params = PricerGraphQueryParams {
            detail_level: "operation".to_string(),
            formula: Some("simple".to_string()),
        };

        let result = get_pricer_graph(State(state), Query(params)).await;
        assert!(result.is_ok());

        let response = result.unwrap();
        assert_eq!(response.graph.nodes.len(), 5);
    }

    #[tokio::test]
    async fn test_get_pricer_graph_scope_level() {
        let state = Arc::new(AppState::new());
        let params = PricerGraphQueryParams {
            detail_level: "scope".to_string(),
            formula: Some("simple".to_string()),
        };

        let result = get_pricer_graph(State(state), Query(params)).await;
        assert!(result.is_ok());

        let response = result.unwrap();
        // Scope level should aggregate to 1 node
        assert_eq!(response.graph.nodes.len(), 1);
    }

    #[tokio::test]
    async fn test_get_pricer_graph_invalid_detail_level() {
        let state = Arc::new(AppState::new());
        let params = PricerGraphQueryParams {
            detail_level: "invalid".to_string(),
            formula: None,
        };

        let result = get_pricer_graph(State(state), Query(params)).await;
        assert!(result.is_err());

        let (status, error) = result.unwrap_err();
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_eq!(error.error_type, "InvalidDetailLevel");
    }

    #[tokio::test]
    async fn test_get_pricer_graph_invalid_formula() {
        let state = Arc::new(AppState::new());
        let params = PricerGraphQueryParams {
            detail_level: "operation".to_string(),
            formula: Some("invalid".to_string()),
        };

        let result = get_pricer_graph(State(state), Query(params)).await;
        assert!(result.is_err());

        let (status, error) = result.unwrap_err();
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_eq!(error.error_type, "InvalidFormula");
    }
}
